### ISSUE TITLE
[Feature Request] Set Default Trigger to Esc+Esc

### ISSUE THREAD

**Issue by luxlogica** [oh-my-fish/plugin-sudope#11]
As mentioned in previous issues - like #8 and #10 - it is very easy for key sequences to clash with other utilities or to be unavailable. In my case - like some of the users reported in Issue #10 - I'm on macOS, and 'Alt+S' just doesn't work. 

The original 'Esc+Esc' sequence from the sudo plugin in oh-my-zsh was a "cumbersome but safe" solution, which AFAIK worked on all platforms (Mac/Win/UX) and conflicted with nothing I can think of. I kindly request, therefore, that:

  1. the default trigger sequence be changed to 'Esc+Esc', and
  2. documentation be added to show the user how to change the key trigger in their config, if they want to.

**Comment by TaChao** [comment]
+1

**Comment by oranja** [comment]
With a long long delay, but perhaps better late than never, Esc+Esc is now the default, but please refer to the README for some caveats.
