### ISSUE TITLE
Errors when cursor is on line below the command

### ISSUE THREAD

**Issue by Strum355** [oh-my-fish/plugin-sudope#3]
When copy-pasting commands from websites, they often have a trailing newline. When i press ctrl+s to add sudo, i get `test: unexpected argument at index 2: ''`  

```
 ~  omf install something
     test: unexpected argument at index 2: ''

```  

fish version: 2.6.0

**Comment by oranja** [comment]
Hi @Strum355,
Sorry for the complete silence.
I was travelling abroad but I'm back now and this error should be gone now.
Let me know how it works for you.

**Comment by Strum355** [comment]
That seems to have fixed it for me :+1: thanks a mil, and thanks for making this plugin!
